### ISSUE TITLE
Several options are ignored / broken

### ISSUE THREAD

**Issue by remimarsal** [arijs/prettier-miscellaneous#13]
After doing some tests it seems at least 2 options are ignored an 1 broken on current binary:

- bracesSpacing (at least from 1.2.2)
- breakBeforeElse (at least from 1.2.2)
- flattenTernaries (at least from 1.3.1)

Here's my test file 
```
class Bambi {
   toto() {
       let tata = true;

       if (tata) { return true; } else { return false; }

       let franckie = `jackie ${tata} ${tata}`;

       return new Promise(resolve => {
           resolve(true);
       });
   }
}
```

Then running `prettier --write --break-before-else --bracket-spacing test1.js`

Output:
```
class Bambi {
   toto() {
       let tata = true;

       if (tata) { 
           return true; 
       } else { 
           return false; 
       }

       let franckie = `jackie ${tata} ${tata}`;

       return new Promise(resolve => {
           resolve(true);
       });
   }
}
```

The output is the same without these flags.

`flattenTernaries` after breaking the ternary will continuously add a linebreak when running several times.

```
toto() {
    let toto = true;
    return toto ? toto : false;
}
```
Output after 3 times:
```
toto() {
    let toto = true;
    return;


        toto ? toto : 
        false;
}
```

**Comment by langdonx** [comment]
I am up for trying to sort some of this out.  I think I just got a handle on how Jest is configured.

Both `bracesSpacing` (affecting `{}`) and `bracketSpacing` (affecting `[]`) appear to work in master (which I think is also 1.4.2), but there aren't tests to cover `bracketSpacing` in this version (the test has been overwritten to only specify `{ bracesSpacing: false }`).

https://github.com/prettier/prettier/blob/master/tests/bracketSpacing/jsfmt.spec.js
vs
https://github.com/arijs/prettier-miscellaneous/blob/master/tests/bracketSpacing/jsfmt.spec.js


@arijs @rhengles What's the process when you guys merge the main trunk back in here?  Cherry picking?  I wonder if it might be good to somehow separate all `prettier-miscellaneous` stuff into separate files/directories so as not to have to diffs?  Separate tests could ensure that everything is still working.

**Comment by remimarsal** [comment]
There's is also an issue with dependencies in package.json.

All the dependencies have been moved to `devDependencies` at some point, even the ones that are required at runtime.

With `npm` or `yarn`, `devDependencies` are not automatically installed.

Pulling the package from npm after version 1.3.1 means I have to manually run `yarn install` in `node_modules/prettier-miscellaneous` to make use of API.

Example:
```
const prettier = require('prettier-miscellaneous');

...

prettier.format(js, options); <--- broken
```

**Comment by rhengles** [comment]
I am sorry I didn't have time to reply this earlier.

@langdonx 

> What's the process when you guys merge the main trunk back in here? Cherry picking?

No, I do a simple merge:

```
git checkout upstream-master
git pull
git checkout prettier-master (my local copy of prettier master branch)
git merge upstream-master
git push
git checkout master
git merge prettier-master --no-commit
npm test
(solve any eventual conflicts...)
git add -A :/
git commit -m "Merge branch 'prettier-master'"
git push
```

**Comment by langdonx** [comment]
> All the dependencies have been moved to `devDependencies` at some point, even the ones that are required at runtime.

That was done on `prettier` as well. https://github.com/prettier/prettier/blob/master/package.json

**Comment by langdonx** [comment]
`bracesSpacing` and `bracketSpacing` appear to work fine in your extension, @remimarsal.

It seems like the `breakBeforeElse` tests are insufficient, as `prettier` itself will `breakBeforeElse` on a brace-less conditional... and the `tests/if/else.js` only has brace-less conditionals.

Unfortunately whenever I modify a test to include braced conditionals, I get a `flow - undefined-verify` error and I'm not sure how to get past it.

Any ideas?

![image](https://user-images.githubusercontent.com/441982/26938662-e172a03e-4c42-11e7-85dd-3c1c8bd7c304.png)

**Comment by remimarsal** [comment]
@langdonx Alrighty I didn't know this way. But how is it supposed to work then? 

Using the API, I get this error `Error: Cannot find module 'esutils'` which is a runtime dependency of Prettier Miscellaneous. I guess having to add the dependency myself in my own package.json is not really an improvement :)

**Comment by langdonx** [comment]
Interesting, it breaks using `prettier-miscellaneous`, but not `prettier` after installing through npm.

I bet it's how the npm package was published... ?

**Comment by langdonx** [comment]
Yea, no "dependencies", but there are "dependents":

https://www.npmjs.com/package/prettier

Neither exist here:

https://www.npmjs.com/package/prettier-miscellenous

I have no idea how to fix that.

**Comment by rhengles** [comment]
@langdonx 

I'm not an expert in Jest, but you can ignore the message `flow - undefined-verify` - in fact this has nothing to do with Flow, it simply means the test is failing according to your screenshot. Unfortunately it doesn't show the name of the test file that failed, so you need to recognize it from the contents of the output.

I think the test is actually right, that is the output you want. You just need to run `npm jest -- -u` to force updating the tests snapshots, and it will save the modified output in the tests.

**Comment by langdonx** [comment]
@rhengles Thanks, I was hand-coding them... `-u` helps.

`flattenTernaries` appears to work in master and your extension as well @remimarsal.  It only breaks them up if they don't fit within `prettier.printWidth` though.

`breakBeforeElse` remains broken though.  @rhengles, did you write it or did someone contribute?

**Comment by langdonx** [comment]
@remimarsal based on your comment/question, I imagine `prettier-miscellaneous` build scripts might be out of date.  Install both through  npm and take a look at each directory.  It looks like `prettier` isn't publishing the repo anymore, but a built directory.  I'm not sure if they've committed that script to their report though?

**Comment by langdonx** [comment]
@rhengles I'm thinking you need to run this `./scripts/build/build.sh` and then npm publish the output of that to npm, not the root of the repo.

**Comment by remimarsal** [comment]
@langdonx According to my tests, there is still an issue with `flattenTernaries` in my extension. What is your test ?

With:
```
return toto ? toto : false;
```
If I save multiple times in VS Code, it will eventually end up like this
```
return;


        toto ? toto :
        false;
```

**Comment by langdonx** [comment]
Ah, curious.  I was using:

`const value = condition1 ? value1 : condition2 ? value2 : condition3 ? value3 : value4;`

`flattenTernaries` definitely has issues w/ `return`.  We should add a test for that.

**Comment by rhengles** [comment]
@langdonx 

> @rhengles I'm thinking you need to run this ./scripts/build/build.sh and then npm publish the output of that to npm, not the root of the repo.

Thank you, will do it as soon as I can.

**Comment by langdonx** [comment]
I made separate issues for the the 2 known (code-related) bugs that came out of here.

Aside from those 2 and the npm issue, I think that everything we discussed here?

**Comment by remimarsal** [comment]
Yes I think we're good ! Closing this thanks @langdonx @rhengles
