### ISSUE TITLE
Runtime dependencies error

### ISSUE THREAD

**Issue by remimarsal** [arijs/prettier-miscellaneous#18]
Hey, just opening a distinct issue for the runtime dependencies error since the package was made dependency-free.

As we discussed, the solution might be to publish only the compiled output of the `dist` directory on npm.

I'm very looking forward we find a solution for this as I'm stuck on version `1.3.1` in my VSCode extension and further versions bring support for TS, Less, Sass and CSS which is awesome.

I tried to build Prettier Misc myself in the node_modules but I cannot reference it as it gets erased while packaging the extension. And of course I'd like to avoid copying the compiled Prettier Misc files or adding Prettier Misc dependencies in my own repo! :)

**Comment by rhengles** [comment]
This should be fixed in 1.4.4:

https://www.npmjs.com/package/prettier-miscellaneous

Thanks! 👍

**Comment by remimarsal** [comment]
Yes that's awesome! 👍 I'll check that out tomorrow.. Thank you Rafael!!
